test:
  num_classes: 1
  seed: -1
  # checkpoint: "models/cableNet.ckpt"
  checkpoint: "models/towelNet.ckpt"
  # checkpoint: "models/needleNet.ckpt"
  wrapper: "SegNetwork"
experiment: "cable_segmentation_test"
camera: "cfg/cameras/zed.yaml"
plug: "cfg/plugs/yumi_plug.yaml"
