dataset_val: "cfg/datasets/cable_seg_val.yaml"
test:
  num_classes: 1
  seed: -1
  checkpoint: "outputs/cable_segmentation_2022-02-16/08-27-11/models/model.ckpt"
experiment: "cable_segmentation_test"
