dataset: "cfg/datasets/towel_seg.yaml"
dataset_val: "cfg/datasets/towel_seg_val.yaml"
train:
  loss:
    name: "SegmentationLoss"
  optimizer:
    optim_learning_rate: 0.001
    decay_gamma: .99
    weight_decay: 0.000001
  num_classes: 1
  seed: -1
  loader_n_workers: 12
  n_gpus: 1
  epochs: 200
  batch_size: 1
  backbone: "UNET"
experiment: "towel_seg_unet"