dataset: "cfg/datasets/towel_seg.yaml"
dataset_val: "cfg/datasets/towel_seg_val.yaml"
train:
  loss:
    name: "SegmentationLoss"
  optimizer:
    optim_learning_rate: 0.002
  num_classes: 1
  seed: -1
  loader_n_workers: 12
  n_gpus: 1
  epochs: 200
  batch_size: 6
experiment: "towel_segmentation"
